### ISSUE TITLE
Application Error When adding <Outlet />

### ISSUE THREAD

**Issue by brianseries** [FrontendMasters/remix-fundamentals#19]
Getting an application error when adding the `Outlet />` component. 

this is in exercise 4 

when doing `node diff` it looks like everything is correct

posting this here in case anybody knows why this is happening 

```
Application Error
Error: Objects are not valid as a React child (found: [object Promise]). If you meant to render a collection of children, use an array instead.
    at renderNodeDestructiveImpl (/Users/b/Public/repos/series-app/remix-fundamentals/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6183:11)
    at renderNodeDestructive (/Users/b/Public/repos/series-app/remix-fundamentals/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6080:14)
    at renderIndeterminateComponent (/Users/b/Public/repos/series-app/remix-fundamentals/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5789:7)
    at renderElement (/Users/b/Public/repos/series-app/remix-fundamentals/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5950:7)
    at renderNodeDestructiveImpl (/Users/b/Public/repos/series-app/remix-fundamentals/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6108:11)
    at renderNodeDestructive (/Users/b/Public/repos/series-app/remix-fundamentals/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6080:14)
    at renderContextProvider (/Users/b/Public/repos/series-app/remix-fundamentals/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5924:3)
    at renderElement (/Users/b/Public/repos/series-app/remix-fundamentals/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6021:11)
    at renderNodeDestructiveImpl (/Users/b/Public/repos/series-app/remix-fundamentals/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6108:11)
    at renderNodeDestructive (/Users/b/Public/repos/series-app/remix-fundamentals/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6080:14)
```

**Comment by brianseries** [comment]
this issue was due to defining the export as async.
