### ISSUE TITLE
Remix: TypeError: Value of "this" must be of type URLSearchParams

### ISSUE THREAD

**Issue by hempun10** [FrontendMasters/remix-fundamentals#28]
### Issue Summary
I'm encountering an issue that persists even after following the recommended steps from a related issue. Specifically, after reading [#6118](https://github.com/remix-run/remix/issues/6118), which suggested that the problem might be due to the Node.js version, I downgraded from Node.js v20 to v18. However, the issue still occurs.

### Steps taken after reading issue
1. Initially, I was using Node.js v20.
2. After encountering the issue, I downgraded to Node.js v18 based on the suggestions in issue #6118.
3. Despite the downgrade, the issue continues to occur.

### Actual Behavior
shows initial remix screen

### Additional Context
Operating System:  macOS 14.4.1
Remix Version: 1.6.7
Node.js Version: (currently v18)
TypeError: Value of "this" must be of type URLSearchParams
    at Proxy.set (node:internal/url:578:13)
    at Proxy.<anonymous> (/Users/himalpun/Developer/remix-fundamentals/node_modules/@remix-run/web-fetch/src/headers.js:124:44)
    at createRemixHeaders (/Users/himalpun/Developer/remix-fundamentals/node_modules/@remix-run/express/dist/server.js:58:17)
    at createRemixRequest (/Users/himalpun/Developer/remix-fundamentals/node_modules/@remix-run/express/dist/server.js:74:14)
    at /Users/himalpun/Developer/remix-fundamentals/node_modules/@remix-run/express/dist/server.js:37:21
    at /Users/himalpun/Developer/remix-fundamentals/node_modules/@remix-run/serve/dist/index.js:48:7
    at Layer.handle [as handle_request] (/Users/himalpun/Developer/remix-fundamentals/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/himalpun/Developer/remix-fundamentals/node_modules/express/lib/router/route.js:144:13)
    at next (/Users/himalpun/Developer/remix-fundamentals/node_modules/express/lib/router/route.js:138:14)
    at next (/Users/himalpun/Developer/remix-fundamentals/node_modules/express/lib/router/route.js:138:14)
GET / 500 - - 193.623 ms

### Request for Help
Does anyone have insights or suggestions on what might be causing this issue? Are there other potential factors besides the Node.js version that I should consider? @kentcdodds

**Comment by chopsueey** [comment]
I encountered the same error. After downgrading node to v18 from v20 with nvm and restarting my vs code it worked.
Using Ubuntu 22.04.4 LTS here

**Comment by somias** [comment]
> I encountered the same error. After downgrading node to v18 from v20 with nvm and restarting my vs code it worked. Using Ubuntu 22.04.4 LTS here

This one worked. Thank you!
